### ISSUE TITLE
Empty "synonyms" on a SlotType value causes Virtual Alexa to error when attempting to "utter"

### ISSUE THREAD

**Issue by leafuk** [bespoken/virtual-alexa#10]
When attempting to call the "utter" function on a created VirtualAlexa, and the interaction model contains a slot value with empty synonyms array, the function will throw an error. When using an utterance that resolves to a slot value that doesn't have a synonyms array, it functions correctly.

For info, when using the Amazon Alexa Skill Builder UI in the developer portal, the default behaviour seems to be to add an empty synonyms array to any slot value created using the UI.

#### index.js

``` index.js
const va = require('virtual-alexa');

const interactionModel = {
    "languageModel": {  
        "intents": [
            {
                "name": "SlottedIntent",
                "samples": ["slot {SlotName}"],
                "slots": [
                    { "name": "SlotName", "type": "SLOT_TYPE" }
                ]
            }
        ],
        "types": [
            {
                "name": "SLOT_TYPE",
                "values": [
                    {
                        "id": null,
                        "name": {
                            "value": "invalid",
                            "synonyms": []
                        }
                    },
                    {
                        "id": null,
                        "name": {
                            "value": "valid"
                        }
                    }   
                ]
            }
        ]
    }
}

const alexa = va.VirtualAlexa.Builder()
    .handler('lambda.handler')
    .interactionModel(interactionModel)
    .create();


alexa.utter('slot invalid')
    .then(response => {
        console.log(response)
    })
    .catch(err => {
        console.log(err);
    });
```

I'm using a simple lambda function to return the intent name and slot value that is passed in:
#### lambda.js 
``` lambda.js
exports.handler = function (event, context, callback) {
    var slot;
    if (event.request.intent && event.request.intent.slots) {
        var slotName = Object.keys(event.request.intent.slots)[0];
        slot = event.request.intent.slots[slotName];
    }

    var response = { success: true, slot: slot };
    if (event.request.intent) {
        response.intent = event.request.intent.name;
    }

    if (event.request.intent && event.request.intent.name == "AMAZON.StopIntent") {
        response.response = { shouldEndSession: true };
    }
    context.done(null, response);
}
```

The expected behaviour should be that the utterance of "Slot invalid" resolves to the "SlottedIntent" with a slot value of "invalid".
`
{ success: true,
  slot: { name: 'SlotName', value: 'invalid' },
  intent: 'SlottedIntent' }
`

The actual response is this:
```
No intentName matches utterance: [object Object]. Using fallback utterance: slot {SlotName}
/home/lea/Code/alexa/va-bug/node_modules/virtual-alexa/lib/src/SkillRequest.js:34
        const isBuiltin = intentName.startsWith("AMAZON");
                                    ^

TypeError: Cannot read property 'startsWith' of undefined
    at SkillRequest.intentRequest (/home/lea/Code/alexa/va-bug/node_modules/virtual-alexa/lib/src/SkillRequest.js:34:37)
    at LocalSkillInteractor.callSkillWithIntent (/home/lea/Code/alexa/va-bug/node_modules/virtual-alexa/lib/src/SkillInteractor.js:91:83)
    at LocalSkillInteractor.spoken (/home/lea/Code/alexa/va-bug/node_modules/virtual-alexa/lib/src/SkillInteractor.js:40:21)
    at VirtualAlexa.utter (/home/lea/Code/alexa/va-bug/node_modules/virtual-alexa/lib/src/VirtualAlexa.js:33:32)
    at Object.<anonymous> (/home/lea/Code/alexa/va-bug/index.js:43:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by jkelvie** [comment]
Hi @leafuk  - thank you for the very clear, detailed writeup. I believe I understand what is happening - I am going to try to reproduce, and if I have more questions I will reach out.

**Comment by jkelvie** [comment]
Closed by #11 - version 0.3.9 released that incorporates it

**Comment by leafuk** [comment]
@jkelvie Thanks so much for the rapid response. Can confirm the latest version has resolved my issue.
Thanks for sharing this library.

**Comment by jkelvie** [comment]
Great, and thanks again for reporting, and the detailed writeup.
