### ISSUE TITLE
TypeError: this.schemaJSON.intents is not iterable

### ISSUE THREAD

**Issue by CoreyCole** [bespoken/virtual-alexa#47]
Using 
```
    "bespoken-tools": "1.2.9",
    "virtual-alexa": "0.5.1",
```
I'm getting
```
      at IntentSchema.intents (node_modules/virtual-alexa/lib/src/IntentSchema.js:19:50)
      at IntentSchema.intent (node_modules/virtual-alexa/lib/src/IntentSchema.js:32:30)
      at IntentSchema.hasIntent (node_modules/virtual-alexa/lib/src/IntentSchema.js:41:21)
      at InteractionModel.hasIntent (node_modules/virtual-alexa/lib/src/InteractionModel.js:69:34)
      at new InteractionModel (node_modules/virtual-alexa/lib/src/InteractionModel.js:20:22)
      at VirtualAlexaBuilder.create (node_modules/virtual-alexa/lib/src/VirtualAlexa.js:105:21)
      at Object.done (src/__tests__/integration.test.ts:27:9)
```
As my intent schema file looks something like this:
```
{
    "interactionModel": {
        "languageModel": {
            "invocationName": "chat",
            "intents": [
                {
                    "name": "LoginIntent",
```
This is the new format as of the ask-sdk version 2 release quite recently.

I was able to hack a fix like this, but not sure if this is what you'd like to do in `IntentSchema.js`:
```javascript
class IntentSchema {
    constructor(schemaJSON) {
        if (schemaJSON.intents) {
            this.schemaJSON = schemaJSON;
        } else if (schemaJSON.interactionModel.languageModel.intents) {
            this.schemaJSON = schemaJSON.interactionModel.languageModel;
        } else {
            throw new Error('unsupported IntentSchema.json file');
        }
    }
// ...
}
```
Running into a different problem with the intent name doing this though, haven't tracked the problem down yet
```
TypeError: Cannot read property 'startsWith' of undefined
```
in `SkillRequest.js` when `const isBuiltin = intentName.startsWith("AMAZON");` is called
```javascript
    intentRequest(intentName) {
        const isBuiltin = intentName.startsWith("AMAZON");
        if (!isBuiltin) {
            if (!this.context.interactionModel().hasIntent(intentName)) {
                throw new Error("Interaction model has no intentName named: " + intentName);
            }
        }
        this.requestJSON = this.baseRequest(RequestType.INTENT_REQUEST);
        this.requestJSON.request.intent = {
            name: intentName,
        };
        if (!isBuiltin) {
            const intent = this.context.interactionModel().intentSchema.intent(intentName);
            if (intent.slots !== null && intent.slots.length > 0) {
                this.requestJSON.request.intent.slots = {};
                for (const slot of intent.slots) {
                    this.requestJSON.request.intent.slots[slot.name] = {
                        name: slot.name,
                    };
                }
            }
        }
        return this;
    }
```

**Comment by jkelvie** [comment]
I don't see how you are calling virtual Alexa. We do support the new
interaction model style, so without seeing that, difficult to guess why it
is not working for you.

-John

**Comment by CoreyCole** [comment]
In your IntentSchema.ts file https://github.com/bespoken/virtual-alexa/blob/master/src/IntentSchema.ts

You are constructing Intents using intentJSON.name
```typescript
    intents() {
        const intentArray = [];
        for (const intentJSON of this.intentList) {
            const intent = new virtual_core_1.Intent(intentJSON.name);
            if (intentJSON.slots !== undefined && intentJSON.slots !== null) {
                for (const slotJSON of intentJSON.slots) {
                    intent.addSlot(new virtual_core_1.IntentSlot(slotJSON.name, slotJSON.type));
                }
            }
            intentArray.push(intent);
        }
        return intentArray;
    }
```

But, in my IntentSchema.json file copy/pasted from alexa console, my intents do not have an `intent` property, they have a `name` property.

To answer your question, I'm providing my intent schema to virtual alexa like this:
```typescript
        alexa = new va.VirtualAlexaBuilder()
            .handler('./init.handler')
            .intentSchemaFile('./speechAssets/IntentSchema.json')
            .sampleUtterancesFile('./speechAssets/SampleUtterances.txt')
            .applicationID(constants.appId)
            .create();
```
where my IntentSchema.json file looks like I pasted above

**Comment by jkelvie** [comment]
If you call interactionModel or interactionModelFile instead of
intentSchema, it will work with the new model.

https://bespoken.github.io/virtual-alexa/api/classes/virtualalexabuilder.html#interactionmodelfile

-John

**Comment by CoreyCole** [comment]
Ah, I see in `InteractionMode.ts` you are mapping the `intent` to `name`
```typescript
// The name of the intent is on the property "name" instead of "intent" for the unified model
intent.intent = intent.name;
```

Thanks for the help! My tests are running now
