### ISSUE TITLE
Jest detects open handles

### ISSUE THREAD

**Issue by CoreyCole** [bespoken/virtual-alexa#83]
I'm using ts-jest to run my virtual-alexa tests. I was running into problems with jest not exiting properly, or returning exit code 0 even when tests were failing. So I added the `--forceExit` and `--detectOpenHandles` flags to my jest testing command. This detected open handles in the `SkillResponse` module seeming to come somewhere from lodash:
```
Jest has detected the following 6 open handles potentially keeping Jest from exiting:

  ●  PROMISE

          at Function.resolve (<anonymous>)
      at Object.<anonymous> (node_modules/lodash/_getTag.js:37:32)
      at Object.<anonymous> (node_modules/lodash/_baseClone.js:12:14)


  ●  PROMISE

          at Function.resolve (<anonymous>)
      at runInContext (node_modules/lodash/lodash.js:6069:36)
      at Object.<anonymous> (node_modules/lodash/lodash.js:17078:11)
      at Object.<anonymous> (node_modules/lodash/lodash.js:17105:3)
      at Object.<anonymous> (node_modules/virtual-alexa/lib/src/core/SkillResponse.js:3:9)


  ●  PROMISE

          at Function.resolve (<anonymous>)
      at Object.<anonymous> (node_modules/lodash/_getTag.js:37:32)
      at Object.<anonymous> (node_modules/lodash/isEmpty.js:2:14)


  ●  PROMISE

          at Function.resolve (<anonymous>)
      at Object.<anonymous> (node_modules/lodash/_getTag.js:37:32)
      at Object.<anonymous> (node_modules/lodash/_baseClone.js:12:14)


  ●  PROMISE

          at Function.resolve (<anonymous>)
      at runInContext (node_modules/lodash/lodash.js:6069:36)
      at Object.<anonymous> (node_modules/lodash/lodash.js:17078:11)
      at Object.<anonymous> (node_modules/lodash/lodash.js:17105:3)
      at Object.<anonymous> (node_modules/virtual-alexa/lib/src/core/SkillResponse.js:3:9)


  ●  PROMISE

          at Function.resolve (<anonymous>)
      at Object.<anonymous> (node_modules/lodash/_getTag.js:37:32)
      at Object.<anonymous> (node_modules/lodash/isEmpty.js:2:14)
```

Here's an example of one of my tests that leads to this issue. All of my intents return promises.
```typescript
test('GeneralHelpIntent should help the user', async () => {
    const deviceId = uuid();
    alexa.context().device().setID(deviceId);
    expect(alexa.context().device().id()).toEqual(deviceId);

    const logoutResponse = await alexa.utter('logout');
    expect(logoutResponse['response'].outputSpeech.ssml).toBeDefined();
    expect(logoutResponse['response'].outputSpeech.ssml).toMatchSnapshot();

    const helpResponse = await alexa.intend('AMAZON.HelpIntent');
    expect(helpResponse['response'].outputSpeech.ssml).toBeDefined();
    expect(helpResponse['response'].outputSpeech.ssml).toMatchSnapshot();

    const launchResponse = await alexa.launch();
    expect(launchResponse['response'].outputSpeech.ssml).toBeDefined();
    expect(launchResponse['response'].outputSpeech.ssml).toMatchSnapshot();

    const loginResponse = await alexa.utter(`My name is ${testConstants.userName}`);
    expect(loginResponse['response'].outputSpeech.ssml).toBeDefined();
    expect(loginResponse['response'].outputSpeech.ssml).toMatchSnapshot();

    const usernameConfirmationResponse = await alexa.utter('yes');
    expect(usernameConfirmationResponse['response'].outputSpeech.ssml).toBeDefined();
    expect(usernameConfirmationResponse['response'].outputSpeech.ssml).toMatchSnapshot();

    const helpResponse2 = await alexa.intend('AMAZON.HelpIntent');
    expect(helpResponse2['response'].outputSpeech.ssml).toBeDefined();
    expect(helpResponse2['response'].outputSpeech.ssml).toMatchSnapshot();

    const joinResponse = await alexa.utter('join channel test');
    expect(joinResponse['response'].outputSpeech.ssml).toBeDefined();
    expect(joinResponse['response'].outputSpeech.ssml).toMatchSnapshot();

    const joinConfirmResponse = await alexa.utter('yes');
    expect(joinConfirmResponse['response'].outputSpeech).toBeUndefined();
    expect(joinConfirmResponse['response'].shouldEndSession).toBeDefined();
    expect(joinConfirmResponse['response'].shouldEndSession).toBeTruthy();

    const helpResponse3 = await alexa.intend('AMAZON.HelpIntent');
    expect(helpResponse3['response'].outputSpeech.ssml).toBeDefined();
    expect(helpResponse3['response'].outputSpeech.ssml).toMatchSnapshot();
}, 15000);
```

**Comment by jkelvie** [comment]
Hi @CoreyCole - I appreciate you reporting this issue, but reading about it, it is not something that is in our control to fix. This issue indicates it is a problem with Jest, which has numerous bugs, none of which do we plan on fixing ourselves (or creating tracking issues for, unless it is something of a critical nature for our project):
https://github.com/cynicaloptimist/improved-initiative/issues/250
